### ISSUE TITLE
over-engineered maybe ?

### ISSUE THREAD

**Issue by squalou** [advantageous/systemd-cloud-watch#24]
I arrived here after a quick search, it's not maintained so I'll post what appears to me as a far more easy solution.

``` journalctl -f >> /var/log/mirror.log ```

put this in a service,
add logrotate if you wish.
then use awslogs to read this file and publish to cloudwatch.

Bonus : you can filter.

``` journalctl -u myUnit -f >> /var/log/mirror-my-unit.log ```

no go to build (it doesn't even build anymore), support multi platform out of the box.

**Comment by rain01** [comment]
Thank you @squalou, for pointing it out.
For everyone who don't know how to do it or just want to save some time, here is how I set it up.

Service to keep putting logs to file:
```
[Unit]
Description=Put journal logs to file for CloudWatch
After=systemd-journald.service

[Service]
ExecStart=/bin/bash -c 'journalctl -f >> /var/log/my-journal.log'
Restart=always
RestartSec=5s

[Install]
WantedBy=multi-user.target
```
Use `-u` to filter if needed, eg:
```
ExecStart=/bin/bash -c 'journalctl -uf sshd >> /var/log/my-auth.log'
```
CloudWatch config to read the log file:
```
{
    "agent": {
        "metrics_collection_interval": 60,
        "run_as_user": "root"
    },
    "logs": {
        "logs_collected": {
            "files": {
                "collect_list": [
                    {
                        "file_path": "/var/log/my-journal.log",
                        "log_group_name": "MY-JOURNALCTL-LOG-GROUP-NAME",
                        "log_stream_name": "{hostname}-{instance_id}"
                    }
                ]
            }
        }
    },
    ...
}
```

And for logrotate, put this in `/etc/logrotate.d/my-journal` file:
```
/var/log/my-journal.log {
    weekly
    rotate 3
    size 10M
    compress
    delaycompress
    notifempty
    minsize 1M
    create
}
```
This will rotate log file every week and keep 3 previous log files, deletes the oldest.

I welcome all the improvements to this.

**Comment by robbytx** [comment]
One pitfall I can see with this is that you can end up with duplicate (recent) or missing (earlier) messages when the `journalctl -f` process is restarted.  You really need some system that tracks its place in the journal to avoid this problem.

Taking a cue from [this blog](https://blog.swwomm.com/2021/06/send-journald-to-cloudwatch-logs-with.html), I've employed [Vector](https://vector.dev/) for this purpose with the following configuration:
```yaml
sources:
  system_logs:
    type: journald
    exclude_units:
      - vector.service # avoid recursive processing
transforms:
  ec2_system_logs:
    type: aws_ec2_metadata
    inputs:
      - system_logs
    fields:
      - instance-id
sinks:
  cloudwatch:
    type: aws_cloudwatch_logs
    inputs:
      - ec2_system_logs
    group_name: MY-JOURNALCTL-LOG-GROUP-NAME
    stream_name: '{{ host }}-{{ "instance-id" }}'
    compression: gzip
    encoding:
      codec: json
      only_fields:
        - message
        - PRIORITY
        - SYSLOG_IDENTIFIER
        - _EXE
        - _PID
        - _UID
```
